// <auto-generated />
namespace StockManagement.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stockindetails_party_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stockindetails_party_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291505256_stockindetails_party_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
