// <auto-generated />
namespace StockManagement.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_party_from_stockindetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_party_from_stockindetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291637333_remove_party_from_stockindetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
