// <auto-generated />
namespace StockManagement.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validaton_check_added_in_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validaton_check_added_in_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081648277_validaton_check_added_in_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
