// <auto-generated />
namespace StockManagement.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sotckin_partyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sotckin_partyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281301082_sotckin_partyadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
